export const SIGN_IN_COPY = {
  title: "Welcome back",
  subtitle: "Sign in to save places, build trips, and pick up where you left off.",
  googleLabel: "Continue with Google",
  facebookLabel: "Continue with Facebook",
  divider: "Or",
  emailLabel: "Email",
  emailPlaceholder: "you@example.com",
  passwordLabel: "Password",
  passwordPlaceholder: "Enter your password",
  rememberMe: "Remember me",
  forgotPassword: "Forgot password?",
  submit: "Sign in",
  submitting: "Signing in…",
  noAccount: "Don't have an account?",
  signUp: "Sign up",
  socialComingSoon: "Social sign-in is coming soon.",
  invalidCredentials: "Invalid email or password.",
  invalidEmail: "Enter a valid email address.",
  passwordRequired: "Enter your password.",
} as const;
