export const SIGN_UP_COPY = {
  title: "Create your account",
  subtitle: "Join GO WITH US to save destinations, build trips, and plan at your own pace.",
  googleLabel: "Continue with Google",
  facebookLabel: "Continue with Facebook",
  divider: "Or",
  fullNameLabel: "Full name",
  fullNamePlaceholder: "Your name",
  emailLabel: "Email",
  emailPlaceholder: "you@example.com",
  passwordLabel: "Password",
  passwordPlaceholder: "Create a password",
  confirmPasswordLabel: "Confirm password",
  confirmPasswordPlaceholder: "Repeat your password",
  termsPrefix: "I agree to the",
  termsLink: "Privacy Policy",
  termsHref: "/privacy",
  submit: "Create account",
  submitting: "Creating account…",
  hasAccount: "Already have an account?",
  signIn: "Sign in",
  socialComingSoon: "Social sign-up is coming soon.",
  invalidEmail: "Enter a valid email address.",
  fullNameRequired: "Enter your full name.",
  passwordRequired: "Enter a password.",
  passwordTooShort: "Password must be at least 8 characters.",
  confirmPasswordRequired: "Confirm your password.",
  passwordsMismatch: "Passwords do not match.",
  termsRequired: "Accept the terms to continue.",
  createError: "We couldn't create your account. Try again or sign in.",
} as const;
