export {
  buildDashboardGreeting,
  DASHBOARD_HEADER_COPY,
  DASHBOARD_HERO_COPY,
  DASHBOARD_HERO_LINKS,
  DASHBOARD_HERO_VISUAL,
  DASHBOARD_MOBILE_TAB_ITEMS,
  DASHBOARD_PROFILE_LINKS,
  DASHBOARD_SIDEBAR_GROUPS,
  DASHBOARD_SIDEBAR_HELP,
  DASHBOARD_SIDEBAR_OFFSET_CLASS,
  DASHBOARD_SIDEBAR_USER_COPY,
  DASHBOARD_SIDEBAR_USER_LINKS,
  DASHBOARD_SIDEBAR_WIDTH_CLASS,
  DASHBOARD_USER,
  type DashboardHeroVisualConfig,
  type DashboardMobileTabItem,
  type DashboardNavItem,
  type DashboardSidebarNavGroup,
  type DashboardSidebarNavItem,
  type DashboardUser,
  EXPLORE_DESTINATION_PANELS,
  EXPLORE_SECTION_COPY,
  EXPLORE_SECTION_LINKS,
  type ExploreDestinationPanel,
  getExploreDestinations,
  getTimeGreeting,
  getUpcomingTrip,
  isDashboardNavActive,
  UPCOMING_TRIP_EMPTY_COPY,
  UPCOMING_TRIP_FIXTURE,
  UPCOMING_TRIP_LINKS,
  UPCOMING_TRIP_SECTION_COPY,
  type UpcomingTrip,
  type UpcomingTripImage,
} from "./dashboard";
