export {
  buildDashboardGreeting,
  DASHBOARD_HEADER_COPY,
  DASHBOARD_MOBILE_TAB_ITEMS,
  DASHBOARD_PROFILE_LINKS,
  DASHBOARD_SIDEBAR_GROUPS,
  DASHBOARD_SIDEBAR_HELP,
  DASHBOARD_SIDEBAR_OFFSET_CLASS,
  DASHBOARD_SIDEBAR_USER_COPY,
  DASHBOARD_SIDEBAR_USER_LINKS,
  DASHBOARD_SIDEBAR_WIDTH_CLASS,
  DASHBOARD_USER,
  type DashboardMobileTabItem,
  type DashboardNavItem,
  type DashboardSidebarNavGroup,
  type DashboardSidebarNavItem,
  type DashboardUser,
  getTimeGreeting,
  isDashboardNavActive,
} from "./dashboard";
