import type { DestinationSeed } from "./helpers.js";

const RAW: Array<
  [
    slug: string,
    title: string,
    country: string,
    region: string,
    city: string,
    lat: number,
    lng: number,
    tier: DestinationSeed["budgetTier"],
    style: string,
    category: string,
  ]
> = [
  [
    "bali",
    "Bali",
    "Indonesia",
    "Southeast Asia",
    "Denpasar",
    -8.3405,
    115.092,
    "moderate",
    "Wellness",
    "Beach",
  ],
  [
    "kyoto",
    "Kyoto",
    "Japan",
    "East Asia",
    "Kyoto",
    35.0116,
    135.7681,
    "moderate",
    "Cultural",
    "History",
  ],
  [
    "lisbon",
    "Lisbon",
    "Portugal",
    "Europe",
    "Lisbon",
    38.7223,
    -9.1393,
    "moderate",
    "Urban",
    "Food",
  ],
  [
    "queenstown",
    "Queenstown",
    "New Zealand",
    "Oceania",
    "Queenstown",
    -45.0312,
    168.6626,
    "luxury",
    "Adventure",
    "Nature",
  ],
  [
    "cape-town",
    "Cape Town",
    "South Africa",
    "Africa",
    "Cape Town",
    -33.9249,
    18.4241,
    "moderate",
    "Nature",
    "Coastal",
  ],
  [
    "labuan-bajo",
    "Labuan Bajo",
    "Indonesia",
    "Southeast Asia",
    "Labuan Bajo",
    -8.4961,
    119.8877,
    "moderate",
    "Adventure",
    "Nature",
  ],
  [
    "venice",
    "Venice",
    "Italy",
    "Europe",
    "Venice",
    45.4408,
    12.3155,
    "luxury",
    "Cultural",
    "History",
  ],
  [
    "cappadocia",
    "Cappadocia",
    "Türkiye",
    "Middle East",
    "Göreme",
    38.6431,
    34.8289,
    "moderate",
    "Adventure",
    "Mountains",
  ],
  [
    "amalfi-coast",
    "Amalfi Coast",
    "Italy",
    "Europe",
    "Amalfi",
    40.634,
    14.6027,
    "luxury",
    "Romantic",
    "Coastal",
  ],
  [
    "marrakech",
    "Marrakech",
    "Morocco",
    "Africa",
    "Marrakech",
    31.6295,
    -7.9811,
    "moderate",
    "Cultural",
    "Food",
  ],
  [
    "bangkok",
    "Bangkok",
    "Thailand",
    "Southeast Asia",
    "Bangkok",
    13.7563,
    100.5018,
    "budget",
    "Urban",
    "Food",
  ],
  ["paris", "Paris", "France", "Europe", "Paris", 48.8566, 2.3522, "luxury", "Art", "Urban"],
  [
    "santorini",
    "Santorini",
    "Greece",
    "Europe",
    "Fira",
    36.3932,
    25.4615,
    "luxury",
    "Romantic",
    "Coastal",
  ],
  ["tokyo", "Tokyo", "Japan", "East Asia", "Tokyo", 35.6762, 139.6503, "luxury", "Urban", "Food"],
  [
    "dubai",
    "Dubai",
    "United Arab Emirates",
    "Middle East",
    "Dubai",
    25.2048,
    55.2708,
    "luxury",
    "Urban",
    "Architecture",
  ],
  [
    "maui",
    "Maui",
    "United States",
    "North America",
    "Kahului",
    20.7984,
    -156.3319,
    "luxury",
    "Nature",
    "Beach",
  ],
  [
    "patagonia",
    "Patagonia",
    "Chile",
    "South America",
    "Puerto Natales",
    -51.7236,
    -72.4878,
    "moderate",
    "Adventure",
    "Mountains",
  ],
  [
    "reykjavik",
    "Reykjavik",
    "Iceland",
    "Europe",
    "Reykjavik",
    64.1466,
    -21.9426,
    "moderate",
    "Nature",
    "Wildlife",
  ],
  [
    "singapore",
    "Singapore",
    "Singapore",
    "Southeast Asia",
    "Singapore",
    1.3521,
    103.8198,
    "luxury",
    "Urban",
    "Food",
  ],
  [
    "hanoi",
    "Hanoi",
    "Vietnam",
    "Southeast Asia",
    "Hanoi",
    21.0278,
    105.8342,
    "budget",
    "Cultural",
    "Food",
  ],
  [
    "seoul",
    "Seoul",
    "South Korea",
    "East Asia",
    "Seoul",
    37.5665,
    126.978,
    "moderate",
    "Urban",
    "Nightlife",
  ],
  [
    "barcelona",
    "Barcelona",
    "Spain",
    "Europe",
    "Barcelona",
    41.3874,
    2.1686,
    "moderate",
    "Art",
    "Urban",
  ],
  [
    "medellin",
    "Medellín",
    "Colombia",
    "South America",
    "Medellín",
    6.2476,
    -75.5658,
    "budget",
    "Urban",
    "Culture",
  ],
  [
    "zanzibar",
    "Zanzibar",
    "Tanzania",
    "Africa",
    "Stone Town",
    -6.1659,
    39.2026,
    "moderate",
    "Beach",
    "Culture",
  ],
  [
    "petra",
    "Petra",
    "Jordan",
    "Middle East",
    "Wadi Musa",
    30.3285,
    35.4444,
    "moderate",
    "History",
    "Adventure",
  ],
  [
    "edinburgh",
    "Edinburgh",
    "United Kingdom",
    "Europe",
    "Edinburgh",
    55.9533,
    -3.1883,
    "moderate",
    "History",
    "Urban",
  ],
  [
    "sydney",
    "Sydney",
    "Australia",
    "Oceania",
    "Sydney",
    -33.8688,
    151.2093,
    "luxury",
    "Coastal",
    "Urban",
  ],
  [
    "mexico-city",
    "Mexico City",
    "Mexico",
    "North America",
    "Mexico City",
    19.4326,
    -99.1332,
    "moderate",
    "Food",
    "Art",
  ],
  [
    "paro",
    "Paro Valley",
    "Bhutan",
    "South Asia",
    "Paro",
    27.4305,
    89.4133,
    "luxury",
    "Wellness",
    "Mountains",
  ],
  [
    "kerala",
    "Kerala",
    "India",
    "South Asia",
    "Kochi",
    9.9312,
    76.2673,
    "budget",
    "Wellness",
    "Nature",
  ],
  [
    "maldives",
    "Maldives",
    "Maldives",
    "South Asia",
    "Malé",
    3.2028,
    73.2207,
    "luxury",
    "Romantic",
    "Beach",
  ],
  [
    "siem-reap",
    "Siem Reap",
    "Cambodia",
    "Southeast Asia",
    "Siem Reap",
    13.3633,
    103.8564,
    "budget",
    "History",
    "Culture",
  ],
  [
    "buenos-aires",
    "Buenos Aires",
    "Argentina",
    "South America",
    "Buenos Aires",
    -34.6037,
    -58.3816,
    "moderate",
    "Nightlife",
    "Food",
  ],
  [
    "vancouver",
    "Vancouver",
    "Canada",
    "North America",
    "Vancouver",
    49.2827,
    -123.1207,
    "moderate",
    "Nature",
    "Urban",
  ],
  [
    "nairobi",
    "Nairobi",
    "Kenya",
    "Africa",
    "Nairobi",
    -1.2921,
    36.8219,
    "moderate",
    "Wildlife",
    "Urban",
  ],
  [
    "muscat",
    "Muscat",
    "Oman",
    "Middle East",
    "Muscat",
    23.588,
    58.3829,
    "moderate",
    "Coastal",
    "Culture",
  ],
  [
    "porto",
    "Porto",
    "Portugal",
    "Europe",
    "Porto",
    41.1579,
    -8.6291,
    "moderate",
    "Food",
    "Coastal",
  ],
  [
    "luang-prabang",
    "Luang Prabang",
    "Laos",
    "Southeast Asia",
    "Luang Prabang",
    19.886,
    102.135,
    "budget",
    "Wellness",
    "Culture",
  ],
  [
    "wadi-rum",
    "Wadi Rum",
    "Jordan",
    "Middle East",
    "Wadi Rum",
    29.532,
    35.419,
    "moderate",
    "Adventure",
    "Desert",
  ],
  [
    "galapagos",
    "Galápagos",
    "Ecuador",
    "South America",
    "Puerto Ayora",
    -0.7393,
    -90.3518,
    "luxury",
    "Wildlife",
    "Nature",
  ],
  [
    "kigali",
    "Kigali",
    "Rwanda",
    "Africa",
    "Kigali",
    -1.9441,
    30.0619,
    "moderate",
    "Culture",
    "Urban",
  ],
  [
    "azores",
    "Azores",
    "Portugal",
    "Europe",
    "Ponta Delgada",
    37.7412,
    -25.6756,
    "moderate",
    "Nature",
    "Islands",
  ],
  [
    "galle",
    "Galle",
    "Sri Lanka",
    "South Asia",
    "Galle",
    6.0535,
    80.221,
    "moderate",
    "Coastal",
    "History",
  ],
  [
    "taipei",
    "Taipei",
    "Taiwan",
    "East Asia",
    "Taipei",
    25.033,
    121.5654,
    "moderate",
    "Food",
    "Urban",
  ],
  [
    "moab",
    "Moab",
    "United States",
    "North America",
    "Moab",
    38.5733,
    -109.5498,
    "moderate",
    "Adventure",
    "Desert",
  ],
  [
    "dubrovnik",
    "Dubrovnik",
    "Croatia",
    "Europe",
    "Dubrovnik",
    42.6507,
    18.0944,
    "luxury",
    "History",
    "Coastal",
  ],
  [
    "palawan",
    "Palawan",
    "Philippines",
    "Southeast Asia",
    "El Nido",
    11.1781,
    119.3896,
    "moderate",
    "Beach",
    "Nature",
  ],
  [
    "kotor",
    "Kotor",
    "Montenegro",
    "Europe",
    "Kotor",
    42.4247,
    18.7712,
    "moderate",
    "Coastal",
    "History",
  ],
  [
    "sossusvlei",
    "Sossusvlei",
    "Namibia",
    "Africa",
    "Sesriem",
    -24.7275,
    15.292,
    "luxury",
    "Adventure",
    "Desert",
  ],
  [
    "ushuaia",
    "Ushuaia",
    "Argentina",
    "South America",
    "Ushuaia",
    -54.8019,
    -68.303,
    "moderate",
    "Adventure",
    "Wildlife",
  ],
];

export const DESTINATION_SEEDS: DestinationSeed[] = RAW.map((entry, index) => {
  const [slug, title, country, region, city, latitude, longitude, budgetTier, style, category] =
    entry;
  const rating = 4.2 + (index % 8) * 0.1;
  const popularity = 72 + (index % 28);

  return {
    slug,
    title,
    country,
    region,
    city,
    latitude,
    longitude,
    budgetTier,
    style,
    category,
    rating,
    popularity,
    featured: index < 12 || index % 7 === 0,
    overview: `${title} blends ${style.toLowerCase()} travel with ${category.toLowerCase()} scenery across ${region}. Plan a few unhurried days around ${city} to feel the rhythm of the place.`,
    highlights: [
      `${style} neighborhoods and viewpoints`,
      `${category} experiences with local guides`,
      `Seasonal highlights around ${city}`,
    ],
    tags: [
      category.toLowerCase(),
      style.toLowerCase(),
      region.split(" ")[0]?.toLowerCase() ?? "travel",
    ],
  };
});
