import type { DestinationListItem } from "@/types/destination";

/** Editorial homepage grid when the catalog API is empty or unreachable (local public imagery). */
export const POPULAR_DESTINATIONS_HOMEPAGE_SHOWCASE: DestinationListItem[] = [
  {
    id: "showcase-karangan-beach",
    slug: "karangan-beach",
    title: "Karangan Beach",
    location: "Labuan Bajo",
    country: "Indonesia",
    region: "Southeast Asia",
    style: "Relaxation",
    category: "Coastal",
    budgetTier: "budget",
    popularity: 88,
    rating: 5.4,
    priceLabel: "$200",
    heroImage: "/landingImg/travelimg/travel-1.jpg",
    imageAlt: "Traveler walking along a wooden pier toward overwater bungalows at Karangan Beach",
  },
  {
    id: "showcase-kepunuh-beach",
    slug: "kepunuh-beach",
    title: "Kepunuh Beach",
    location: "Bali",
    country: "Indonesia",
    region: "Southeast Asia",
    style: "Relaxation",
    category: "Coastal",
    budgetTier: "moderate",
    popularity: 91,
    rating: 4.5,
    priceLabel: "$250",
    heroImage: "/landingImg/travelimg/travel-2.jpg",
    imageAlt: "Aerial view of palm-lined Kepunuh Beach with turquoise water",
  },
  {
    id: "showcase-marrakech",
    slug: "marrakech",
    title: "Marrakech",
    location: "Marrakech",
    country: "Morocco",
    region: "Africa",
    style: "Cultural",
    category: "Urban",
    budgetTier: "moderate",
    popularity: 86,
    rating: 4.6,
    priceLabel: "$260",
    heroImage: "/landingImg/travelimg/travel-3.jpg",
    imageAlt: "Vibrant market spices and colorful goods in Marrakech",
  },
  {
    id: "showcase-lumukutan-beach",
    slug: "lumukutan-beach",
    title: "Lumukutan Beach",
    location: "Natuna",
    country: "Indonesia",
    region: "Southeast Asia",
    style: "Relaxation",
    category: "Coastal",
    budgetTier: "budget",
    popularity: 82,
    rating: 5.4,
    priceLabel: "$200",
    heroImage: "/landingImg/travelimg/travel-4.jpg",
    imageAlt: "Crescent white sand and blue water at Lumukutan Beach",
  },
  {
    id: "showcase-kyoto",
    slug: "kyoto",
    title: "Kyoto",
    location: "Kyoto",
    country: "Japan",
    region: "East Asia",
    style: "Cultural",
    category: "Historic",
    budgetTier: "moderate",
    popularity: 94,
    rating: 4.7,
    priceLabel: "$270",
    heroImage: "/landingImg/travelimg/travel-5.jpg",
    imageAlt: "Traditional Kyoto street with wooden architecture and soft morning light",
  },
  {
    id: "showcase-scottish-highlands",
    slug: "scottish-highlands",
    title: "Scottish Highlands",
    location: "Highlands",
    country: "United Kingdom",
    region: "Europe",
    style: "Adventure",
    category: "Mountain",
    budgetTier: "moderate",
    popularity: 89,
    rating: 4.5,
    priceLabel: "$250",
    heroImage: "/landingImg/travelimg/travel-6.jpg",
    imageAlt: "Open road through misty Scottish highlands with rolling hills",
  },
];
